// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARpfVas4Uho0AOCrKLPWTiKyd0P6Oncgw',
    appId: '1:411840954251:android:c1f3aaf02d6b8f57a7b98e',
    messagingSenderId: '411840954251',
    projectId: 'chatapp-c6875',
    storageBucket: 'chatapp-c6875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1jSx7MHQHlFsDhPTyBT3P9Q-Xogtqi8',
    appId: '1:411840954251:ios:560f0cb386d6418aa7b98e',
    messagingSenderId: '411840954251',
    projectId: 'chatapp-c6875',
    storageBucket: 'chatapp-c6875.appspot.com',
    androidClientId: '411840954251-ap8fl2301rpoqd7s4n5h9gd2ntvc3nkl.apps.googleusercontent.com',
    iosClientId: '411840954251-h419659ukkipnggncfquc5fnb68qkhtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
